---
- block: # Performance Tuning
  - name: Configure security limits
    lineinfile:
      dest: /etc/security/limits.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ tuning_limits_vars }}"
    when: tuning_enabled and tuning_limits_vars is defined
    register: tuning_configure_security_limits

  - name: Configure sysctl.conf
    lineinfile:
      dest: /etc/sysctl.conf
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ tuning_sysctl_vars }}"
    when: tuning_enabled and tuning_sysctl_vars is defined
    register: tuning_configure_sysctl

  - name: Tuning hugepage
    lineinfile:
      dest: /etc/rc.local
      state: present
      insertbefore: ^exit 0$
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ tuning_rc_vars }}"
    when: tuning_enabled and tuning_rc_vars is defined
    register: tuning_configure_hugepage

  - name: Check if server need to reboot
    set_fact:
      tuning_need_reboot: true
    when: |
      tuning_configure_security_limits.changed
      or tuning_configure_sysctl.changed
      or tuning_configure_hugepage.changed

  tags:
    - host-preparation-tuning
